import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const notoSansJP = Noto_Sans_JP(
  {
    variable: "--font-noto-sans",
    subsets:["latin"],
    weight:["400"]
  }
)

export const metadata: Metadata = {
  title: "Book commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable} ${notoSansJP.variable} antialiased`}
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
